### PR TITLE
Remove NetlifyCMS

### LINKED ISSUE #24: kill admin panel
It encourages bad practices - e.g. uploading assets into a single directory, writing bad markdown w/o running pre-commit hooks, etc.

It does not solve the problem - it's not WYSIWYG, it confuses users.

It complicates the deployment process - need GitHub auth, etc.

It's not that hard to run yarn develop and user any editor to write text.

### PR DESCRIPTION
**Pull request by iAdramelk**
Fix #24

### CODE REVIEW

**Comment by iAdramelk** [comment]
Should we also move images from the `uploads` to the corresponding folders as a part of his PR?

**Comment by shcheklein** [comment]
> Should we also move images from the uploads to the corresponding folders as a part of his PR?

could you clarify a bit please?

**Comment by iAdramelk** [comment]
@shcheklein Right now all images for posts and authors are stored in the `/static/upload/` folder. we can move them to closer to content.

For example we can rename `/content/blog/2017-05-15-how-a-data-scientist-can-improve-his-productivity.md` to `/content/blog/2017-05-15-how-a-data-scientist-can-improve-his-productivity/index.md` and place all images in the same folder `/content/blog/2017-05-15-how-a-data-scientist-can-improve-his-productivity/`.

**Comment by shcheklein** [comment]
@iAdramelk how about authors? sill in static? it sounds good to me to move them nearby

**Comment by iAdramelk** [comment]
@shcheklein we can move them too.

**Comment by shcheklein** [comment]
@iAdramelk I mean i'm 👍 on moving post images. Not sure about authors. It was just a question. Probably it makes sense to keep them separate.

**Comment by shcheklein** [comment]
@iAdramelk let's merge and create a separate ticket to migrate images?

**Pull request merged**
